name: silk
description: Something to split and join files.
# version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 path: ^1.7.0
 args: ^2.0.0
 ansicolor: ^2.0.1

dev_dependencies:
 pedantic: ^1.9.0

executables:
 silk: main
